### ISSUE TITLE
Filtrar tweets mostrados en el mapa: pide ayuda / ofrece ayuda

### ISSUE THREAD

**Issue by pepellou** [pepellou/ayuda-alimentos-coronavirus#17]
La idea es con algún tipo de botón sobre el mapa ver sólo la gente que pide ayuda o ver sólo la gente que ofrece ayuda. 

Creo que puede ser útil según cuál sea el caso del usuario ver sólo el caso contrario.

**Comment by kdarrey** [comment]
Se marcan con clases css cada tipo de elemento.
Se añande un botón para cada tipo y se añaden los controles para marcar ocultar según la selección

**Comment by pepellou** [comment]
Fixed by #59
